### ISSUE TITLE
crash with libcd 3.0.2 for 1.16.2

### ISSUE THREAD

**Issue by shaox97** [TechReborn/RebornCore#161]
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'libcd'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'libcd' provided by 'techreborn'
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:163)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:246)
	at io.github.cottonmc.libcd.LibCD.onInitialize(LibCD.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 11 more
Caused by: java.lang.NoClassDefFoundError: io/github/cottonmc/libcd/api/tweaker/Tweaker
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:156)
	... 14 more
Caused by: java.lang.ClassNotFoundException: io.github.cottonmc.libcd.api.tweaker.Tweaker
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 20 more

**Comment by modmuss50** [comment]
Looks like the mod was rewritten.. so the libcd support will need to be rewirrten. for now use the older version

**Comment by shaox97** [comment]
It is a relief that old version libcd works with 1.16.2.

**Comment by drcrazy** [comment]
LibCD abandoned
